### ISSUE TITLE
zh.vec文件缺失

### ISSUE THREAD

**Issue by YangFan0407** [JiaxiangBU/rumor_detection_2019_ncovEX#1]
你好，我在尝试运行你的代码时，发现有个zh.vec文件，请问这个文件是哪里来的？我在比赛网站上并没有看到这个文件呀。
应该是自己做的中文词向量文件，请问能开源吗？   

2.1 加载训练好的词向量  中，第一行
`zh_model = KeyedVectors.load_word2vec_format('../data/zh.vec')`

**Comment by JiaxiangBU** [comment]
@YangFan0407 

> 你好，我在尝试运行你的代码时，发现有个zh.vec文件，请问这个文件是哪里来的？我在比赛网站上并没有看到这个文件呀。
> 应该是自己做的中文词向量文件，请问能开源吗？
> 
> 2.1 加载训练好的词向量 中，第一行
> `zh_model = KeyedVectors.load_word2vec_format('../data/zh.vec')`

你好，这个文件我是参考 @wshuyi

文件较大，怕影响大家 clone，你可以参考这个地址下载

https://github.com/JiaxiangBU/demo-chinese-text-classification-lstm-keras/blob/master/zh.zip
